version: "3"
services:

  web:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/fio/
    environment:
      DATABASE_URL: "postgres://ariadne:fio-de@db/fio-de-ariadne"

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fio-de-ariadne
      POSTGRES_PASSWORD: fio-de
      POSTGRES_USER: ariadne
